#!/bin/bash

help() {
  echo "Usage:"
  echo "  gvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # echo $PLUGIN_GVM_GO_BIN
  [ -s "$ZMICRO_HOME/plugins/gvm/source" ] && \. $ZMICRO_HOME/plugins/gvm/source
  echo "$GO_HOME/bin"
}

run() {
  core $@
}

run $@
