#!/bin/bash

help() {
  echo "Usage:"
  echo "  gvm exec <version> <command> [args]"
  echo ""
  echo "Example:"
  echo "  gvm exec v1.20 go version"
  echo "  gvm exec v1.18 go build"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  gvm::exec $@
  if [ "$?" != "0" ]; then
    log::error "failed to exec: $@"
    exit 1
  fi
}

run() {
  core $@
}

run $@
