#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_GVM_NAME)
  echo "Go Version Manager ($(color::success $version))"
}

description() {
  echo "Go Version Manager is a tool for managing multiple Go versions."
}

usage() {
  echo "Usage:"
  echo "  zgvm install <version>   - Install Go version"
  echo "  zgvm use <version>       - Use Go version"
  echo "  zgvm remove <version>    - Remove Go version"
  echo "  zgvm ls                  - List the Go versions installed"
  echo "  zgvm ls-remote           - List all Go versions from remote"
  echo "  zgvm current             - Show current Go version"
  echo "  zgvm exec                - Enter new shell with go version for tmp"
  echo "  zgvm help                - Show help"
}

example() {
  echo "Example:"
  echo "  zgvm install $PLUGIN_GVM_GO_DEFAULT_VERSION"
  echo "  zgvm use $PLUGIN_GVM_GO_DEFAULT_VERSION"
  echo "  zgvm remove $PLUGIN_GVM_GO_DEFAULT_VERSION"
  echo "  zgvm ls"
  echo "  zgvm ls-remote"
  echo "  zgvm current"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
