#!/bin/bash

help() {
  echo "Usage:"
  echo "  zgvm install <version>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1

  gvm::install $@

  log::success "install ${name} success"
}

run() {
  core $@
}

run $@
