#!/bin/bash

help() {
  echo "Usage:"
  echo "  gvm shell <version> "
  echo ""
  echo "Example:"
  echo "  gvm shell v1.20"
  echo "  gvm shell v1.18"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  gvm::shell $@
}

run() {
  core $@
}

run $@
