#!/bin/bash

# gvm::current gets the current version of Go
gvm::current() {
  [ -s "$ZMICRO_HOME/plugins/gvm/source" ] && \. $ZMICRO_HOME/plugins/gvm/source

  if [ "$(os::has_command go)" != "true" ]; then
    return
  fi

  echo "$PLUGIN_GVM_GO_CURRENT_VERSION ($(go version))"
}

export -f gvm::current
